#cloud-config
timezone: Asia/Tokyo
locale: ja_JP.utf8

groups:
    - docker
system_info:
    default_user:
        groups: [docker]

package_upgrade: true
packages:
    - docker.io
    - avahi-daemon

runcmd:
    - curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
    - sudo apt update
    - sudo apt install gh

ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBAK2dUjVdeA6/FfcfmsYGCNinLjMa71Li6AlhjsVd1ajWgOWwEanUJ9Yxbg+p77npfZOlosud+ZIuDDGR2aVi74Ido6cGJXYBRbLhB2G1hqMoCPhxmMh6aaNrL50047TJNBBcKY+WkWSYDWoKjJeNXptlrD8Dnf2NI09Ai8NAMxmagW6OjIRfsQCGT3ESc/bCMP+HrzspImhCJ/51bYiRZdGPIQQDS4qZqTQvh2Yi2WCUT5bHW3eWtnSm5rdxnAkJEnwvX47Ccv3NM/G2HV4IrHic4RwKDQ28M89+oP2nmhCG8hxhxkrx/8O7mHFljtTcvD2k2GTn3ZK/l1WB0Kzh stakme@air.stak.me
